### ISSUE TITLE
Squares not highlighted for Euclidean movement

### ISSUE THREAD

**Issue by chr-s-p** [manuelVo/foundryvtt-drag-ruler#143]
With the newest updates, squares doesn't highlight at all when using Euclidean diagonal movement. Also, the value is not rounded like it used to, it shows with two decimal digits which is a bit ugly.

It was functional in 1.9.1, but doesn't work in either 1.10.1 or 1.10.2 :)

**Comment by manuelVo** [comment]
The highlighting of squares was disabled for euclidean measurements on purpose. This has been done because highlighting squares cannot be made to work properly on scenes with euclidean measurement style. This is because measurement is completely decoupled from the grid. One corner of a square measures as another distance than some other corner of the same square. This can lead to the same square needing to be colored in two different colors, which isn't possible. As a viable alternative to coloring the squares, the ruler's color will now change accordingly, instead of coloring the squares, like it does on gridless scenes. This also helps visualize, that the measurement is decoupled from the grid.

**Comment by chr-s-p** [comment]
I guess that somehow makes sense, however I didn't notice any errors with it in 1.9.1, which I currently rolled my server back to. Do you plan to change the significant digits on the value back to no decimals? :)

**Comment by manuelVo** [comment]
Things break once you try to place your token unsnapped from the grid (can be done with shift). In 1.9.1, every pixel inside a grid cell will have the same measurement.

I haven't fully decided on how to handle the rounding issue yet. I can see pros and cons to both rounding and not rounding it.

**Comment by chr-s-p** [comment]
I never place tokens unsnapped from the grid, but I see how some people could do it. Regarding the rounding issue, maybe add it as a option in the settings?

Anyway, I am closing this issue now, thanks for your responses :)
