### ISSUE TITLE
Pathfinding by default?

### ISSUE THREAD

**Issue by dmrickey** [manuelVo/foundryvtt-drag-ruler#149]
I was wanting this to be more of a discussion than a request, but I didn't know where else to start it, so I'll just open this issue here. Would it be possible to have pathfinding be the default? As in if my player starts dragging a token it shows the line as normal, but then as soon as he crosses a wall, it automatically starts adding in waypoints to counteract this? I've got one player that always runs into problems with walls that don't block line of sight (like for instance an upper level that overlooks a balcony), he'll see that the area is visible and try to walk through it, or if there are narrow paths he inevitable always runs his path through a wall, and foundry rejects the whole movement. So is there a way to turn this into the default drag movement without any other keypresses?

**Comment by manuelVo** [comment]
That functionality is already included Drag Ruler and can be enabled in the module settings.

Please note that a bug in Drag Ruler 1.11.2 made that setting disappear on the player clients (it can still be set via the console by entering `game.settings.set("drag-ruler", "autoPathfinding", true/false)`). The bug is fixed in 1509307313d857af861ea37a98a0a2d30d5067cf and that fix will be part of the 1.11.3 bugfix release.
