### ISSUE TITLE
[BUG] - Drag Rule causes CanvasAnimation.getAnimation promise to resolve immediately

### ISSUE THREAD

**Issue by Haxxer** [manuelVo/foundryvtt-drag-ruler#156]
**Describe the bug**
Drag Ruler seems to override core behavior relating to animation promises on token animations; the promises are immediately resolved rather than waiting for the animation to finish before resolving them. It would be ideal if Drag Ruler could preserve this functionality.

**To Reproduce**
1. Create a macro with the following content:
```js
Hooks.once("updateToken", async (doc) => {
    await CanvasAnimation.getAnimation(doc.object.movementAnimationName).promise;
    console.log("Animation finished");
});
```
2. Run macro
3. Drag token across scene
4. "Animation finished" will be printed into the console immediately
5. Disable module
6. Repeat steps 1 to 3
7. See the "Animation finished" message appears after the animation finished

**Expected behavior**
The promise should resolve only after the animation has finished.

**Setup:**
 - Foundry Version: 9.249
 - OS: Windows
 - Browser: Chrome 97.0.4692.99

**Comment by dmrickey** [comment]
As an avid user of both Sequencer and Dragruler, it would be awesome if this could be sorted out

**Comment by manuelVo** [comment]
It appears Foundry has (thankfully) changed the way tokens are animated along rulers. I'll need to adjust Drag Ruler to use the new code as well, which should make this bug disappear.

This code is caused because two animations will be started. The second animation will immediately cancel the first animation, which will therefore end.

A workaround for the time being would be this:
```javascript
function sleep(ms) {
  return new Promise(resolve => window.setTimeout(resolve), ms);
}

Hooks.once("updateToken", async (doc) => {
    await sleep(200);
    await CanvasAnimation.getAnimation(doc.object.movementAnimationName).promise;
    console.log("Animation finished");
});
```
This waits a little while so the first animation has been cancelled and the second one is started and will then await until the second animation is done.
