### ISSUE TITLE
Error when dragging animated token.

### ISSUE THREAD

**Issue by Ikabodo** [manuelVo/foundryvtt-drag-ruler#159]
![image](https://user-images.githubusercontent.com/7766890/154449197-ab867cfa-cdb7-4c9d-968f-479e0d61b949.png)
![image](https://user-images.githubusercontent.com/7766890/154450341-e0eb572f-4e11-4607-85bc-90e5ce922e6a.png)

Since the last update (?) I'm getting this error when I try to drag tokens. Happens with only libwrapper and dragruler active. 

Interesting notes:
* Only happens on a certain token/actor, I haven't been able to tell what is different about it. It MIGHT be that the token uses a webm, an animated token.
* It throws 5-10 errors each time the token is dragged.
* The token bugs out after dragging.

**Comment by Ikabodo** [comment]
Just had this error too, not sure if it's related:
![image](https://user-images.githubusercontent.com/7766890/154451090-dda05cf2-e287-4281-93ab-37bab14428ad.png)

**Comment by manuelVo** [comment]
Just to be sure: Does this bug disappear if you disable Drag Ruler?

If so, please share a screenshot of the "Appearance"-Tab of the affected token.

**Comment by Ikabodo** [comment]
I must admit, I didn't even check with just libwrapper. But it actually happens with just libwrapper active. I guess this is a bug with that module. :)

**Comment by Ikabodo** [comment]
Even seems to be a core issue. Interesting. I'll close this.

**Comment by manuelVo** [comment]
It's likely that your token is corrupt. Apparently it's missing the "scale" attribute, which shouldn't happen. It's hard to say what caused this token to become corrupted. It might as well be some module that did something nasty to the token in the past that made it break. Tracking down the real culprit is really difficult in such a situation. If it only affects a single token I'd suggest deleting and re-creating the token, which should fix the bug and if this never happens again, just ignore it as a one-off fluke.
