### ISSUE TITLE
Feature Request: Configurable token width modifier for gridless pathfinding

### ISSUE THREAD

**Issue by schultzcole** [manuelVo/foundryvtt-drag-ruler#193]
With some gridless maps, the walls are arranged such that a gap is just *barely* too small for the radius of a token, preventing users from pathfinding through the gap. I think it might be useful to have a global configuration setting to specify the percentage of a token's width that it can "squeeze" through.

So the GM would specify that the token width percentage is 80% (or whatever slider value they want), and that would mean that a 1x1 token could fit through a gap that is .8 grid units wide or larger.

From what I've seen in the code, it seems like this would only affect gridless pathfinding, but I might have missed something. If you're amenable to this, I can create a PR to add this feature.

**Comment by manuelVo** [comment]
I fully agree that barely too small hallways shouldn't be an issue to pathfind through.

The main issue I'm seeing with this is that the average user likely won't get what the point of the setting is. I'd like to keep the settings menu for the module as lean and useful as possible, so the question would be where to put the setting or how to present it to not burden the average user.

Another possibility could be to just set a fixed token width percentage that makes sense and not offering a setting. I imagine there aren't many useful values for that setting anyway, since ultimately the setting only affects two things:
- The smaller the value, the smaller the gap a token can squeeze trough
- The smaller the value, the closer the token cuts corners (which starts looking ridiculous at some point)

Maybe there is a nice sweet spot we can find where tokens can squeeze through gaps that are just barely too small, while still maintaining a sensible distance when moving around corners?

If you have a good solution, feel free to create a PR :)

**Comment by schultzcole** [comment]
Hmm, yeah for the majority of users it probably would not be very useful. I think maybe setting a default of 90% of the token size or so would be reasonable. I would suggest having it as a setting, but not showing it in the settings config, so that users who want to customize it can do so through a macro or the console, but most users can ignore it.

I'll have a PR up for it this evening.

**Comment by manuelVo** [comment]
Btw only gridless is affected by this, so you don't need to search through the gridded pathfinding code
