### ISSUE TITLE
Speed provider for PF1 fail.

### ISSUE THREAD

**Issue by misterchristophertoo** [manuelVo/foundryvtt-drag-ruler#242]
when using the Speed Setting Provider for system pathfinder 1, any attempt to move a token errors out and on provides a basic purple measurement when moving.

works as expected with the generic settings but, obviously, doesn't recognize different speed types.

**Comment by manuelVo** [comment]
Please open the javascript console (opens with F12) and see if there are any errors or warning. If so, please post a screenshot of them.

**Comment by misterchristophertoo** [comment]
<img width="705" alt="Screen Shot 2022-10-15 at 12 55 38 PM" src="https://user-images.githubusercontent.com/85243367/195998627-70111fa0-1536-4f8a-b71a-80f1bf7c7f75.png">
ta-da, happens every time you touch a token

**Comment by manuelVo** [comment]
The speed provider within Pathfinder 1 hasn't been updated for v10. I've handed in a Pull Request in their repo to fix that. With that, the speed provider functionality should hopefully be restored with one of the next Pathfinder 1 releases.

I'm closing this issue, because it's not directly related to the Drag Ruler module.
