### ISSUE TITLE
[Feature Request] Integration with Savage Worlds Adventure Edition

### ISSUE THREAD

**Issue by olytron** [manuelVo/foundryvtt-drag-ruler#244]
Wonderful Module!

- Character movement is equal to Pace
- Running, increase pace by Running die

I don't know if this is possible, but thanks for looking into it!

**Comment by manuelVo** [comment]
Drag Ruler will not implement any game system specific rules. However, it offers an [API](https://github.com/manuelVo/foundryvtt-drag-ruler#api) that game systems and third party modules can use to inform Drag Ruler about the specific rules of their system, which allows those modules to make Drag Ruler neatly integrate into any given game system. If you're capable of doing some coding yourself I encourage you to have a look at writing such an integration module yourself - it's usually a pretty simple thing to do. Otherwise, maybe ask in the SWADE channel of the official Foundry discord. Maybe someone is already working on such a module (or is interested in doing so).
