### ISSUE TITLE
V11 Compatibility

### ISSUE THREAD

**Issue by apoapostolov** [manuelVo/foundryvtt-drag-ruler#273]
Drag Ruler breaks movement in V11, the module needs to be updated to the new version.

**Comment by radiantorange** [comment]
Same. This is duplicated [here](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/270)

**Comment by TookieKun** [comment]
Thanks to another user's instructions I did the work of editing the code to work for V11 and also fixed the issue of not being able to create waypoints with dragruler 

https://github.com/TookieKun/foundryvtt-drag-ruler-partial-v11-compability

Just replace the files with the ones I modified and it should work just fine.

**Comment by pkonshik** [comment]
Why don't you create PR with these changes?

**Comment by UndeadChiller** [comment]
> Drag Ruler breaks movement in V11, the module needs to be updated to the new version.

Same.

**Comment by CokaColaOase** [comment]
> Thanks to another user's instructions I did the work of editing the code to work for V11 and also fixed the issue of not being able to create waypoints with dragruler
> 
> https://github.com/TookieKun/foundryvtt-drag-ruler-partial-v11-compability
> 
> Just replace the files with the ones I modified and it should work just fine.

Could you create a release on your fork so that the patched module can be installed via the module installer in the Foundry setup screen? (For those of us who are hosting on Forge, @TookieKun) 

Not sure if this really is what is required, but that's at least the difference between your fork and that of Traumi who did a great fork for V10.

Thank you!

**Comment by manuelVo** [comment]
A v11 compatible version has just been released.
