### ISSUE TITLE
Ensure all tokens selected tokens are moved simultanously on laggy maps

### ISSUE THREAD

**Issue by Stendarpaval** [manuelVo/foundryvtt-drag-ruler#28]
I notice that there's often considerable lag when starting to click and drag a token and when it finally starts to move along with the cursor. The ShowDragDistance module performs more smoothly right now, while providing similar base functionality. To be fair, the lag is most noticeable when using lots of modules like FXmaster, etc.

In addition, when moving a group of tokens, they move one-by-one to the new location. This takes very, very long - especially when there's lag as mentioned above. It would be nice if there was a setting to turn this behavior off. 

I'm using Foundry v0.7.9 and the dnd5e system v1.2.4. My map sizes are fairly large and often feature lots of tokens, because I'm running a megadungeon.

**Comment by manuelVo** [comment]
Drag Ruler is designed to move all the tokens simultaneously. However the tokens aren't moved as a group, but instead each token takes care of the movement for itself. However if a token needs a long time to start it's movement that would indeed case them to move one-by-one. So it's likely that addressing the performance issue will also fix the issue with tokens not moving simultaneously.

Regarding the performance issue: In all the worlds I have Drag Ruler performs smoothly. However I'm lacking worlds with huge maps with many tokens that I could use for testing / reproducing this issue. Can you send me the world that's causing your issues, so I can take a look at it? The easiest for me to work with would be if you could share your whole Foundry Data folder (only the world-folder with a list of modules you use in that world would do as well though).

You can privately send me the data using this link: https://wolke.ccn.li/s/jbyw8CB7d6eCysB

**Comment by Stendarpaval** [comment]
I've sent you a .zip file of a test world I made based on my world. It's called `test-world-drag-ruler.zip`.  I would've sent you the entire world, but a lot of the assets I  use in it are stored outside of the world folder, so it would either be a lot of work to sort out or become a gigantic upload... So I chose to compromise. From what I can tell, the performance issue persists in that test world, even if there's only a single scene. 

I've also included this list of modules I usually have active: [module_list.txt](https://github.com/manuelVo/foundryvtt-drag-ruler/files/6062878/module_list.txt). However, even with all modules deactivated save Drag Ruler, the issue is still there.

(Apologies for the barrage of random files in your nextcloud - I didn't notice that the folder with the world had become unzipped after downloading it from my own server. ^^;)

**Comment by manuelVo** [comment]
Thanks for providing this test world to me. I can reproduce the problem in that world and will see what I can do about it.

Don't worry about the random files that got uploaded. Everything went into a dedicated folder, so it was easy to discard of everything that wasn't needed :)

**Comment by manuelVo** [comment]
I've done some initial testing on this and it appears, that most of the lag issues are actually caused by foundry itself. The lag happening when selecting, deselecting and dragging tokens seems to also appear when disabling the Drag Ruler module. It appears that the only thing that I could do to improve the situation is to make the tokens all move at the same time. Can you confirm that this is the case?

**Comment by Stendarpaval** [comment]
Thanks for investigating! 

The results I find kind of curious, because I was sure that ShowDragDistance performed more smoothly... but perhaps I was biased by the incremental movement of groups of tokens being so slow. 

To be fair, the scene I sent you is one of the largest maps in the campaign (though they’re all pretty big), so I don’t think there’ll be as much slowdown from Foundry in the future. 

Having said that, it’d be a great timesaver if you could somehow add a setting that makes multiple tokens move at the same time. :)

**Comment by manuelVo** [comment]
I'll treat this issue as a request to ensure that all tokens will move simultaneously, even if the map is laggy, since that's the only issue that I was able to attribute to Drag Ruler. If you encounter other performance issues other than this that can be attributed to Drag Ruler feel free to open another issue.

**Comment by manuelVo** [comment]
I just tried to implement this, but the attempt was futile. The new implementation suffers from the same issues as the old one. And I came to the conclusion that this issue cannot be solved with reasonable effort (considering that the issue is mainly caused by the poor performance that foundry provides on larger maps and considering that this is a rather niche issue). If you want this fixed, please file a ticket about the performance issues in the foundry issue tracker.

It's also worth to mention that I've taken another look at Show Drag Distance. The reason why Show Drag Distance feels faster is because Show Drag Distance disables itself when you drag multiple tokens at once. So Show Drag Distance isn't actually faster when dragging multiple tokens but more precisely not present at all.

**Comment by Stendarpaval** [comment]
Thanks for your efforts, that must have been a frustrating exercise. I'll close this issue and consider filing a ticket in the Foundry issue tracker. 

And interesting that Show Drag Distance turns itself off. I've experienced some other minor bugs with it, so I've switched to Drag Ruler anyway. I'm also trying to lower the number of actors that are loaded in, maybe that'll help in the interim.

**Comment by manuelVo** [comment]
I gave this another shot and was able to improve the situation a lot in 26917200. This will be part of Drag Ruler v1.6.0.
