### ISSUE TITLE
Doppleganger effect when dragging tokens

### ISSUE THREAD

**Issue by KhorneOnTheCob** [manuelVo/foundryvtt-drag-ruler#312]
https://github.com/manuelVo/foundryvtt-drag-ruler/assets/159863772/3d0e9ae3-26ae-4ee6-8119-2b03a8567aa0

been having issues with drag ruler in the 11.315 Foundry and 5.13.6 pf2e system. When I drag the token to a new position it creates the double unselectable token that makes it so I can't move the token anymore.

**Comment by manuelVo** [comment]
I cannot reproduce this on my system. This bug is likely caused by a conflict between two modules. You can do the following to find out which modules are responsible for this: Install and activate the "Find the Culprit" module. You will then have a new button in your module management window called "Find the Culprit". Click it. In the window that opens, activate the checkbox for the modules socketlib and Drag Ruler. Then press start.

You will now be guided through a multi-step process where Find the culprit activates and deactivates your modules and asks you after each step if the bug still persists. Go through that process and Find the Culprit will tell you a name of a module that is causing the bug (possibly because it's conflicting with drag ruler). Once we know the other module that is involved we can work from there.

**Comment by KhorneOnTheCob** [comment]
Was able to remove the issue by deactivating modules and activating them one at a time. However which one I cannot say as I essentially did the manual way of doing "Find the Culprit"'s module. It at the least started when I downloaded Reyzor's package of pf2e action support engines, but that's active again with no conflicts. If I ever do identify what caused this I'll mention it again, but this issue isn't persisting luckily.
