### ISSUE TITLE
Gridless snapping snaps to incorrect increments

### ISSUE THREAD

**Issue by BoltsJ** [manuelVo/foundryvtt-drag-ruler#336]
On gridless scenes, the snap increments are significantly inaccurate, and can snap too close or too far. It's hard to tell if there's any sort of pattern as consecutive moves in roughly the same direction will have different amounts of error. The error happens on both chromium and firefox.
![image](https://github.com/user-attachments/assets/d61dd32d-79b6-4da9-b609-991236c43e63)
![Screenshot from 2024-07-28 13-25-42](https://github.com/user-attachments/assets/b32a898d-5e94-484a-8251-a7fd421a0003)
![Screenshot from 2024-07-28 13-25-58](https://github.com/user-attachments/assets/a410058d-833b-4eea-8233-73b135af20cf)

There are no console errors, but there are an overwhelming number of deprecation warnings.

**Comment by n0q** [comment]
This is affecting me, too. I can't use drag ruler in its present state. 

I'm pretty sure this happens, superficially, due to `ruler.rulerOffset`. On v11, there was an offset calculation so that if you grabbed a token off-center, the endpoints would be auto-adjusted to the token center. On v12, this is no longer necessary, so that rulerOffset was double-correcting, and removed. Unfortunately, it seems like the offset is still needed for grid snapping.

That is to say, if you grab the token dead center, it'll 'mostly work'. One hacky way to resolve this would be to use `ruler.rulerOffset` but only for calculating grid snap endpoints. It would get most people going, at least.
