### ISSUE TITLE
Abillity to swap space/right click behaviour.

### ISSUE THREAD

**Issue by DipsoNOR** [manuelVo/foundryvtt-drag-ruler#4]
I find it more convenient to set way-points with the mouse(This is also the default behaviour in show drag distance) is there any chance there could be an option to swap these buttons in the module settings?.

**Comment by KevinRichard-GM** [comment]
I second the motion. All my players and myself I find it easier to use the right click for waypoints as that is the more used function then deleting previous waypoints (backspace maybe if you want to leave spacebar to set also).

**Comment by manuelVo** [comment]
In attempting to implement this I realized that this actually requires me to rewrite the whole dragging logic of foundry, so I'm postponing this to a later release.

**Comment by apoapostolov** [comment]
I also join this topic because I thought waypointing was impossible in Drag Ruler because I couldn't do it with the right button as I am used from Show Drag Distance. This is a huge must to retain my and my player's habits as currently we switched back to Show Drag Distance because of this.

**Comment by dmrickey** [comment]
Yeah I agree, space is not intuitive, I thought this wasn't a feature until I went back to check it and then came here to write up this same request.

@manuelVo I'm curious why it would take rewriting the dragging logic? I mean I don't know anything about how it's implemented in Foundry, but couldn't you just listen for a mouse click up event and add a waypoint like what happens with the current implementation of hitting space? Like I said I know nothing about how Foundry is doing it but it seems odd that you can do it with a key event but not a mouse event.

**Comment by manuelVo** [comment]
Right click to set waypoints actually pretty easy. The hard part of the swap is deleting the waypoints with space (or more precisely cancelling the drag when there are no waypoints left). Foundry itself cancels drags with right click (hence the decision to use right click to cancel in Drag Ruler as well). This means that for canceling via spacebar I cannot forward the event to foundry and let it do all the work, but must implement the cancel logic myself (like removing the ghost and stopping the dragging, so that releasing doesn't move the token)

**Comment by dmrickey** [comment]
That makes sense. Thanks for the detailed answer. P.s. The latest release looks like it has a lot of good content in it. Especially this feature. It's a great module so thanks for putting it together for everyone 👍
