### ISSUE TITLE
modify speed when you leave a difficult terrain

### ISSUE THREAD

**Issue by Awinckler** [manuelVo/foundryvtt-drag-ruler#52]
Hi,
For the moment the speed is modify when you go on a case but is it possible to modify or add an option to change the speed when you leave it?

**Comment by manuelVo** [comment]
Hi. I'm sorry, but I didn't quite understand what the feature you're requesting is. Can you try and rephrase the request? Thanks :)

**Comment by Awinckler** [comment]
Yep no problem
I request something as it explain in this module. ( https://github.com/Nordiii/difficultterrain ).
But for the moment it's not compatible with your module.

**Comment by manuelVo** [comment]
Which part of that module would you like supported by Drag Ruler? Measuring difficult terrain in general? Or being able to adjust the Terrain's difficulty level manually without having to place down difficult terrain using TerrianLayer?

**Comment by Awinckler** [comment]
measuring difficult terrain.
I have instaled the terrain ruler module so it's globaly work but in PF2 the distance is double when you leave the case and not when you enter in.
And for the moment it seems it is not the case.

**Comment by manuelVo** [comment]
According to PF2 rules the cost is doubled when entering difficult terrian, not when leaving it
> Moving into a square of difficult terrain [...] costs an extra 5 feet of movement.

https://2e.aonprd.com/Rules.aspx?ID=453

Of course you can play however you want, I'm just stating that fact here for completeness sake.

In any case, this would be a feature that you would request in the Terrain Layer module (as that's the module for calculating difficult terrain). For this reason I'm closing this issue here, but feel free to open a new issue in the [Terrain Ruler](https://github.com/manuelVo/foundryvtt-terrain-ruler) repository about this.
