### ISSUE TITLE
Integrate with Enhanced Terrain Layer to account for token disposition when dragging over another token.

### ISSUE THREAD

**Issue by Doresain** [manuelVo/foundryvtt-drag-ruler#54]
I don't know how this might apply to other rulesets, but for 5e at least:
`You can move through a nonhostile creature's space. In contrast, you can move through a hostile creature's space only if the creature is at least two sizes larger or smaller than you. Remember that another creature's space is difficult terrain for you.`

Would be killer if, when using the Enhanced Terrain Layer module, dragging across another token either treated it as difficult terrain OR 'blocked' movement (turning ruler red) depending on the dispositions of the tokens.

I filed #[basically the same issue](https://github.com/ironmonk88/enhanced-terrain-layer/issues/9) with ironmonk88 over at Enhanced Terrain Layer. I am incredibly ignorant as to exactly what information is being passed between ETL, Terrain Ruler, and Drag Ruler to support the 'other tokens are difficult terrain' feature. That said, it seems to me that:
1. Drag ruler has to know what token it is dragging, and so could check its disposition.
2. ETL knows what token is being dragged over (maybe?) and so could provide some information about its disposition.
3. Either Drag Ruler or Terrain Ruler (???) are figuring out from what point a ruler should be colored red

It seems like the correct logic would be something like:
- If moving token is FRIENDLY and crossed token is
-- FRIENDLY, difficult terrain
-- NEUTRAL, difficult terrain
-- HOSTILE, movement blocked (ruler turns red from that point)
- If moving token is HOSTILE and crossed token is
-- FRIENDLY, movement blocked
-- NEUTRAL, difficult terrain
-- HOSTILE, difficult terrain
- If moving token is NEUTRAL, any crossed token is difficult terrain
- If you wanted to be really fancy, there's be some comparison between token actor sizes as well given the 'two sizes larger or smaller' rule.

I don't know which module it makes sense for the logic layer to live in? Anyway I'm leaving this here to get your mind working. If you're interested enough to pursue it and ironmonk88 is interested enough to pursue it, it seems like the kind of thing that could be hashed out and solved for.

Thanks again for the great module(s).

**Comment by manuelVo** [comment]
I completely understand that with that bunch of modules working so closely together it's difficult to discern what module is responsible for what. :)
Your request need to be implemented into either of these two modules
- *Enhanced Terrain Layer* since it already provides the setting to treat tokens as difficult terrain (and also does the necessary calculations for that) it could add options to make that more granular - like adding size rules or token disposition settings.
- *A DnD5e integration module for Drag Ruler*: Drag Ruler has an [API](https://github.com/manuelVo/foundryvtt-drag-ruler#api) that allows other modules and game systems to make Drag Ruler aware of the rules for the active game system. Such a module could make Drag Ruler use the fly speed for creatures that are currently flying, swimming speed over water, and define rules for which tokens count as difficult terrain and which don't (for example depending on their size). Note however that such a integration module currently doesn't exist for DnD5e, so you would need to find someone interested in writing it first (or do it yourself, if you're capable of doing such a thing).

Drag Ruler itself is the wrong place for such a feature, since Drag Ruler is a game system agnostic module that does not (and will never if I do something about it) contain any game system specific features.

**Comment by ironmonk88** [comment]
I think even adding size rules or token disposition is system specific.
I like the idea but it pretty much sits with the system specific ruler.
