### ISSUE TITLE
Dragging over tokens creates difficult terrain as expected sorta

### ISSUE THREAD

**Issue by Avitale34** [manuelVo/foundryvtt-drag-ruler#56]
I really am loving the new updates it seems like it is recognizing tokens as difficult terrain but I noticed a small bug if you are taking your first diagonal it should be 5ft however if your first diagonal is into a space where another token is located it is calculated at "15ft" instead of 10ft" like its adding an extra 10ft instead of 5ft due to a token being there.

**Comment by manuelVo** [comment]
Are you using the 5/10/5 grid rule?

**Comment by Avitale34** [comment]
Yes I am using that rule setting

**Comment by manuelVo** [comment]
That behavior is intentional. The semantic of difficult terrain is that a step into difficult terrain costs twice as much as a regular step. That means if you step into difficult terrain diagonally, you have to pay the cost of two diagonals. The first diagonal under 5/10/5 costs 5ft., the second 10ft - this sums up to the 15ft. that Drag Ruler charges for a diagonal step into difficult terrain.

In fact this way of calculating diagonal costs for difficult terrain are in line with Pathfinder 1 rules as well. If you have a game system that charges a different cost for diagonal steps into difficult terrain, please open an issue in the Terrain Ruler repository (since Terrain Ruler is the module that is performing the difficult terrain calculations).
