### ISSUE TITLE
Rangefinder ability?

### ISSUE THREAD

**Issue by clifftacopter** [manuelVo/foundryvtt-drag-ruler#6]
One cool feature from Show Drag Distance was the rangefinder ability. Pressing CTRL while you had a token selected would draw a ruler between the selected token and the current location of your mouse. Any possibility of adding a similar feature in Drag Ruler? Thanks for all your hard work!!

**Comment by manuelVo** [comment]
I'm still undecided on whether I want to implement this into Drag Ruler or not. One of the reasons I was never very fond of this feature in ShowDragDistance is that placing it on CTRL collides with the ruler shortcut from native foundry. Also while agree that the idea for the feature is cool I'm not sure if it fits good into the scope of this plugin. Then again it probably wouldn't be very difficult to implement. At this point I can not make any gurantees to whether I will implement this at some point or not.

**Comment by caewok** [comment]
I agree that the rangefinder feature was really useful. Also agree that CTRL was not the best choice of keys. For me, it was super-useful for both GMs and PCs to determine range for ranged-weapon attacks.

**Comment by chozma** [comment]
I personally only use ShowDragDistance for the rangefinder while keeping the titular feature off, since not only is it great for seeing distances, but you can also use movement with the rangefinder the same way anyway by setting waypoints, and without an (IMO) intrusive ruler appearing whenever you drag a token even in situations where you don't need it. Having it on the Ctrl key also works perfectly for me since there couldn't be a more convenient key for it to be bound to, and I never really use the default Foundry ruler, but I do use rangefinder constantly.

Perfectly understandable if it's not a feature you'd like to implement, of course! But just giving my 2 cents as a user who is very fond of it. Was quite confused at first seeing this made out to be a replacement for ShowDragDistance, since I couldn't see any mention of any of the features I use for it (nor any support for multiple movement speeds). Been worried about it no longer working since I really rely on it.

**Comment by manuelVo** [comment]
I've just released the [Rangefinder](https://foundryvtt.com/packages/rangefinder) module, which provides this functionality as a standalone module and is compatible with Drag Ruler. With the release of that module I'm considering this issue as resolved.
