### ISSUE TITLE
Bug: movement skips during combat when "Not Your Turn!" is enabled

### ISSUE THREAD

**Issue by luisjs** [manuelVo/foundryvtt-drag-ruler#84]
When combat is started and "Block Combat Movement" is on, dragging tokens results in very jumpy movement:

![20210616_213658](https://user-images.githubusercontent.com/7376474/122289966-2ea2f500-ceeb-11eb-8a9b-dc461d200808.gif)

- FoundryVTT v0.8.7 (but reproducible in 0.8.6)
- Drag Ruler v1.7.3
- Not Your Turn! v1.1.5
- socketlib v1.0.6

**Comment by manuelVo** [comment]
The same behavior happens in Not your Turn, when Drag Ruler is disabled and you try to move the token using Ctrl+Drag+Spacebar, so this is actually a bug in that module. Please request support for Ctrl+Drag+Spacebar movement in the Not your Turn repository. If that is implemented, Drag Ruler should work as well (since Drag Ruler replicates the Ctrl+Drag+Spacebar functionality).
