### ISSUE TITLE
[SWADE Bug] Can't Detect Change in Pace (speed)

### ISSUE THREAD

**Issue by brunocalado** [manuelVo/foundryvtt-drag-ruler#93]
If you got wound in SWADE you reduce your movement. 

But, drag ruler don't notice that.

https://user-images.githubusercontent.com/4999783/124954204-3b979d80-dfec-11eb-839b-aecaa557b07b.mp4

**Comment by manuelVo** [comment]
All that Drag Ruler does to determine the ruler color is reading the attribute that's configured in the Speed Provider Settings. The value that's configured there by default is what I've been told would work for SWADE. To make Drag Ruler's Generic Speed Provider respect the changes in speed, we need to configure a attribute that reports the speed value that's adjusted for wounds. If such a value exists I'll happily update Drag Ruler's default for SWADE accordingly. However I'd need someone to find out the name of that attribute for me, since I'm not fimiliar at all with the SWADE game system and it's rules.

If there is no such value in the SWADE system there is one other possibility to get the speed adjustment on wounded characters working: Drag Ruler offers an [API](https://github.com/manuelVo/foundryvtt-drag-ruler#api) that can be used to write custom Speed Providers. A custom speed provider can be tailored to a specific game system, allowing for a deep integration of a game systems rules into drag ruler. Writing such a Speed Provider is fairly simple (as you can see in the example in the API documentation) and the Speed Provider can be distributed either as a separate module or can be directly integrated into the corresponding game system.

**Comment by brunocalado** [comment]
Hi.

There was an update.

Can you switch to `actor.data.data.stats.speed.adjusted` for swade?

Thank you.
